spring.application.name=SubTrack

ai.max-output-tokens=8000
ai.max-retries=3

ai.main-provider.provider=mistral
ai.main-provider.model-name=open-mistral-nemo
ai.main-provider.api-key=overwritten-on-server

ai.backup-provider.provider=gemini
ai.backup-provider.model-name=gemini-3.1-flash-lite
ai.backup-provider.api-key=overwritten-on-server